


# Site settings
title: Bob Baxley
email: bob@rjbaxley.com
author: Bob Baxley
description: Bob Baxley
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://rjbaxley.com" # the base hostname & protocol for your site
twitter_username: Bob_Baxley
github_username:  gte620v
exclude: [vendor,'*.ipynb']

# Build settings
markdown: kramdown


kramdown:
  input: GFM


paginate: 5



collections:
  about_pages:
    output: false

